using Pkg
ENV["PYTHON"] = "~/.conda/envs/py38/bin/python"

Pkg.add("BenchmarkTools")
Pkg.add("Conda")
Pkg.add("DSP")
Pkg.add("Distributions")
Pkg.add("Documenter")
Pkg.add("DocumenterTools")
Pkg.add("FFTW")
Pkg.add("FITSIO")
Pkg.add("Formatting")
Pkg.add("Healpix")
Pkg.add("IJulia")
Pkg.add("Interpolations")
Pkg.add("LaTeXStrings")
Pkg.add("LsqFit")
Pkg.add("MPI")
Pkg.add("NPZ")
Pkg.add("PkgTemplates")
Pkg.add("Plots")
Pkg.add("ProgressMeter")
Pkg.add("PyCall")
Pkg.add("PyPlot")
Pkg.add("ReferenceFrameRotations")
Pkg.add("Revise")
Pkg.add("StatPlots")
Pkg.add("StaticArrays")
Pkg.add("StatsBase")
Pkg.add("StatsPlots")
Pkg.add("TickTock")
Pkg.add("LinearAlgebra")
Pkg.add("HDF5")
Pkg.add("WignerD")
Pkg.add("WignerFamilies")
Pkg.add("Statistics")
Pkg.add("LoopVectorization")


